version: "3"
services:
  neo4j:
    image: neo4j:2026.02.2
    container_name: neo4j
    environment:
      NEO4J_AUTH: neo4j/password
      NEO4J_dbms_connector_bolt_advertised__address: bolt.neo4j.pfi.local.dev-gutools.co.uk:443
    volumes:
      - neo4j:/var/lib/neo4j/data
    ports:
      - 7474:7474
      - 7687:7687

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.2
    container_name: pfi-elasticsearch
    environment:
      - discovery.type=single-node
      - network.publish_host=127.0.0.1
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms4g -Xmx4g"
      - xpack.security.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elasticsearch:/usr/share/elasticsearch/data
    ports:
      - 9200:9200

  cerebro:
    image: lmenezes/cerebro:0.9.3
    container_name: pfi-cerebro
    ports:
      - 9092:9000
    command: '-Dconfig.file=/opt/cerebro/conf/cerebro.conf'
    volumes:
      - ${PWD}/util/local-cerebro.conf:/opt/cerebro/conf/cerebro.conf

  garage:
    image: dxflrs/garage:v2.3.0
    container_name: garage
    restart: unless-stopped
    volumes:
      - ./infra/garage/garage.toml:/etc/garage.toml:ro
      - garage-data:/var/lib/garage/data
      - garage-meta:/var/lib/garage/meta
    environment:
      GARAGE_DEFAULT_ACCESS_KEY: "garage-user"
      GARAGE_DEFAULT_SECRET_KEY: "reallyverysecret"
      # to make garage work with a default user we need to specific a default bucket
      GARAGE_DEFAULT_BUCKET: "unused-bucket"
    ports:
      - 3900:3900
      - 3903:3903
    command: /garage server --single-node --default-bucket

  garage-ui:
    image: noooste/garage-ui:latest
    container_name: garage-ui
    restart: unless-stopped
    ports:
      - 9091:8080
    depends_on:
      - garage
    environment:
      # Garage S3 Configuration
      GARAGE_UI_GARAGE_ENDPOINT: "garage:3900"
      GARAGE_UI_GARAGE_ADMIN_ENDPOINT: "http://garage:3903"

      # Server Configuration
      GARAGE_UI_SERVER_HOST: "0.0.0.0"
      GARAGE_UI_SERVER_PORT: "8080"
      GARAGE_UI_SERVER_ENVIRONMENT: "production"
      GARAGE_UI_GARAGE_ADMIN_TOKEN: "secret"
      GARAGE_UI_GARAGE_REGION: "garage"

  postgres:
    image: postgres:15.3
    # make sure there's enough memory to run VACUUM
    shm_size: 1g
    ports:
      - 8432:5432
    environment:
      - POSTGRES_USER=giant_master
      - POSTGRES_PASSWORD=giant
      - POSTGRES_DB=giant
    volumes:
      - postgres-data:/var/lib/postgresql/data
    command:
      ["postgres", "-c", "log_statement=all", "-c", "random_page_cost=1.5"]

volumes:
  neo4j:
    driver: local

  elasticsearch:
    driver: local

  garage-data:
    driver: local

  garage-meta:
    driver: local

  postgres-data:
    driver: local
