# Find full documentation here https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions
name: CI

on:
  # Manual invocation.
  workflow_dispatch:

  # None of the projects in this build are in use so all auto-building is disabled
#  push:
#  pull_request:

jobs:
  CI:
    runs-on: ubuntu-latest

    # See https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token
    permissions:
      # required by aws-actions/configure-aws-credentials
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4

      # Setup AWS credentials to enable uploading to S3 for Riff-Raff.
      # See https://github.com/aws-actions/configure-aws-credentials
      - uses: aws-actions/configure-aws-credentials@v4
        name: setup-riffraff-credentials
        with:
          role-to-assume: ${{ secrets.GU_RIFF_RAFF_ROLE_ARN }}
          aws-region: eu-west-1
          unset-current-credentials: true

      # Setup Node, checking common Node config files to determine the version of Node to use.
      # Configuring caching is also recommended.
      # See https://github.com/guardian/actions-setup-node
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc

      # Configuring caching is also recommended.
      # See https://github.com/actions/setup-java
      - name: Setup Java 8
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'

      # 1. Seed the build number with last number from TeamCity.
      #    Update `LAST_TEAMCITY_BUILD` as needed or remove entirely if changing Riff-Raff project name.
      # See https://github.com/github/scripts-to-rule-them-all
      - name: Run script/teamcity
        run: |
          LAST_TEAMCITY_BUILD=5000
          export BUILD_NUMBER=$(( $GITHUB_RUN_NUMBER + $LAST_TEAMCITY_BUILD ))
           ./scripts/teamcity.sh
