# Find full documentation here https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions
name: CI

on:
  # Manual invocation.
  workflow_dispatch:

  push:

jobs:
  CI:
    runs-on: 4core-ubuntu-latest-arm-giant

    # See https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token
    permissions:
      # required by aws-actions/configure-aws-credentials
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version-file: '.java-version'
          distribution: corretto
          cache: sbt

      - name: Install sbt
        uses: sbt/setup-sbt@v1

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: npm
          cache-dependency-path: frontend/package-lock.json

      - name: Run script/ci.sh to build artefacts
        run: ./scripts/ci.sh

      - name: Put artifacts in the right place
        run: |
          mkdir -p pfi pfi-cli pfi-public-downloads
          mv backend/target/pfi_0.1.0-SNAPSHOT_all.deb pfi/pfi.deb
          mv cli/target/pfi-cli_0.1.0-SNAPSHOT_all.deb pfi-cli/pfi-cli.deb
          mv cli/target/universal/pfi-cli-0.1.0-SNAPSHOT.tgz pfi-public-downloads/pfi-cli.tar.gz

      - name: Upload for playground
        uses: guardian/actions-riff-raff@v4
        with:
          projectName: investigations::pfi-playground
          roleArn: ${{ secrets.GU_RIFF_RAFF_ROLE_ARN }}
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          buildNumberOffset: 5000
          contentDirectories: |
            pfi:
              - pfi/pfi.deb
            pfi-cli:
              - pfi-cli/pfi-cli.deb
            pfi-public-downloads:
              - pfi-public-downloads/pfi-cli.tar.gz
          configPath: riff-raff.yaml
          commentingEnabled: 'false'

      - name: Edit riff-raff file prior to re-upload
        run: sed -i -e "s/pfi-playground/pfi-giant/g" riff-raff.yaml

      - name: Upload for giant
        uses: guardian/actions-riff-raff@v4
        with:
          projectName: investigations::pfi-giant
          roleArn: ${{ secrets.GU_RIFF_RAFF_ROLE_ARN }}
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          buildNumberOffset: 5000
          contentDirectories: |
            pfi:
              - pfi/pfi.deb
            pfi-cli:
              - pfi-cli/pfi-cli.deb
            pfi-public-downloads:
              - pfi-public-downloads/pfi-cli.tar.gz
          configPath: riff-raff.yaml
          commentingEnabled: 'false'

      - name: Reset checkout just in case
        run: sed -i -e "s/pfi-giant/pfi-playground/g" riff-raff.yaml
