# Find full documentation here https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions
name: CI

on:
  # Manual invocation.
  workflow_dispatch:

  push:

jobs:
  CI:
    runs-on: 4core-ubuntu-latest-arm-giant

    # See https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token
    permissions:
      # required by aws-actions/configure-aws-credentials
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4

      # Setup AWS credentials to enable uploading to S3 for Riff-Raff.
      # See https://github.com/aws-actions/configure-aws-credentials

      ############################################################
      ## THIS SECTION IS TO BE REMOVED WHEN RIFF RAFF ACTION WORKS
      ############################################################
      - uses: aws-actions/configure-aws-credentials@v4
        name: setup-riffraff-credentials
        with:
          role-to-assume: ${{ secrets.GU_RIFF_RAFF_ROLE_ARN }}
          aws-region: eu-west-1

      # TODO: configure caching
      # See https://github.com/actions/setup-java
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version-file: '.java-version'
          distribution: corretto
          cache: sbt

      - name: Install sbt
        run: |
          sudo apt-get update
          sudo apt-get install apt-transport-https curl gnupg -yqq
          echo "deb https://repo.scala-sbt.org/scalasbt/debian all main" | sudo tee /etc/apt/sources.list.d/sbt.list
          echo "deb https://repo.scala-sbt.org/scalasbt/debian /" | sudo tee /etc/apt/sources.list.d/sbt_old.list
          curl -sL "https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x2EE0EA64E40A89B84B2DF73499E82A75642AC823" | sudo -H gpg --no-default-keyring --keyring gnupg-ring:/etc/apt/trusted.gpg.d/scalasbt-release.gpg --import
          sudo chmod 644 /etc/apt/trusted.gpg.d/scalasbt-release.gpg
          sudo apt-get update
          sudo apt-get install sbt

      # TODO: configure caching
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: npm
          cache-dependency-path: frontend/package-lock.json

      - name: Run script/ci.sh to build artefacts
        run: ./scripts/ci.sh

      - name: Upload for playground
        uses: guardian/actions-riff-raff@v4
        with:
          projectName: investigations::pfi-playground
          roleArn: ${{ secrets.GU_RIFF_RAFF_ROLE_ARN }}
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          buildNumberOffset: 5000
          contentDirectories: |
            backend:
              - backend/target/pfi_0.1.0-SNAPSHOT_all.deb
            cli:
              - cli/target/pfi-cli_0.1.0-SNAPSHOT_all.deb
              - cli/target/universal/pfi-cli-0.1.0-SNAPSHOT.tgz
          configPath: riff-raff.yaml
          commentingEnabled: 'false'

      - name: Edit riff-raff file prior to re-upload
        run: sed -i -e "s/pfi-playground/pfi-giant/g" riff-raff.yaml

      - name: Upload for giant
        uses: guardian/actions-riff-raff@v4
        with:
          projectName: investigations::pfi-giant
          roleArn: ${{ secrets.GU_RIFF_RAFF_ROLE_ARN }}
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          buildNumberOffset: 5000
          contentDirectories: |
            backend:
              - backend/target/pfi_0.1.0-SNAPSHOT_all.deb
            cli:
              - cli/target/pfi-cli_0.1.0-SNAPSHOT_all.deb
              - cli/target/universal/pfi-cli-0.1.0-SNAPSHOT.tgz
          configPath: riff-raff.yaml
          commentingEnabled: 'false'

      - name: Reset checkout just in case
        run: sed -i -e "s/pfi-giant/pfi-playground/g" riff-raff.yaml
